<?php

function controller_permission(){
    return array(
    'administer jaycees controller' => array(
      'title' => t('Administer Jaycees controller'),
      'description' => t('Administer Jaycees configurations options.'),
    ),
  );
}

function controller_menu(){
  $items = array();
  
  $items['admin/config/controller'] = array(
    'title' => 'Jaycees Controller Config',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('controller_admin_form'),
    'access arguments' => array('administer jaycees controller'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  return $items;
}

function controller_admin_form($node, &$form_state){
  $form = array();
  
  $form['google_maps_api_key'] = array(
    '#title' => 'Google settings',
    '#type' => 'textfield',
    '#description' => t('Google developer maps api key.'),
    '#default_value' => variable_get('google_maps_api_key',''),
  );
  
  return system_settings_form($form);
}