<?php

function controller_permission(){
  
  $items = array();

  $items['administer jaycees controller'] = array(
    'title' => t('Administer Jaycees controller'),
    'description' => t('Administer Jaycees configurations options.'),
  );
  
  $items['administer jaycees controller'] = array(
    'title' => t('Administer Jaycees events'),
    'description' => t('Change event types for events content type'),
  );

}

function controller_menu(){
  $items = array();
  
  $items['admin/config/jaycees'] = array(
    'title' => 'Configure Jaycees Options',
    'description' => 'Allows administrators to configure various Jaycees options',
    'weight' => -100,
    'position' => 'left',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc', 
    'file path' => drupal_get_path('module', 'system'),
  );
  
  $items['admin/config/jaycees/controller'] = array(
    'title' => 'Jaycees Controller Config',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('controller_admin_form'),
    'access arguments' => array('administer jaycees controller'),
  );
  
  $items['admin/config/jaycees/event_types'] = array(
    'title' => 'Jaycees Event Types',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('controller_event_types_form'),
    'access arguments' => array('administer jaycess events'),
  );
  
  return $items;
}

function controller_admin_form($form, &$form_state){
  $form = array();
  
  $form['google_maps_api_key'] = array(
    '#title' => 'Google settings',
    '#type' => 'textfield',
    '#description' => t('Google developer maps api key.'),
    '#default_value' => variable_get('google_maps_api_key',''),
  );
  
  return system_settings_form($form);
}

function controller_event_types_form($form, &$form_state){

  $form = array();
  
  $form['crj_event_types'] = array(
    '#title' => 'Event Types',
    '#type' => 'textarea',
    '#description' => t('Event types when creating an event. Types preceded with a "#" will not appear in the list. Example - #Uptown Friday Nights'),
    '#default_value' => variable_get('crj_event_types',''),
  );

  return system_settings_form($form);
  
}