<?php
/**
 * @file
 * Code for the crj_events feature.
 */

include_once 'crj_events.features.inc';

function crj_events_form_alter(&$form, &$form_state, $form_id){
  if($form_id == 'event_node_form'){
    $options = array();
      
    $values = variable_get('crj_event_types','');
    
    $values = explode(PHP_EOL,$values);
    
    foreach($values as $item){
      if(strpos($item,'#') !== 0){
        $key = preg_replace('/\s+/', '', $item);
        $options[strtolower(trim($key))] = $item;
      }
    }
    
    $form['field_event_type']['und']['#options'] = $options;
    
    $form['#validate'][] = 'crj_events_node_validate';
  
  }
}

function crj_events_node_validate($form, &$form_state){
  if(!empty($form_state['values']) && !empty($form_state['values']['field_event_redirect']['und'][0]['value'])){
    $node = node_load($form_state['values']['field_event_redirect']['und'][0]['value']);
    if(!isset($node->type)){
      form_set_error('field_event_redirect','Node does not exist. Please enter a valid node.');
    }
  }
}