<?php
/**
 * @file
 * Code for the crj_events feature.
 */

include_once 'crj_events.features.inc';

function crj_events_form_alter(&$form, &$form_state, $form_id){
  if($form_id == 'event_node_form'){
    $options = array();
      
    $values = variable_get('crj_event_types','');
    
    $values = explode(PHP_EOL,$values);
    
    foreach($values as $item){
      if(strpos($item,'#') !== 0){
        $key = preg_replace('/\s+/', '', $item);
        $options[strtolower(trim($key))] = $item;
      }
    }
    
    $form['field_event_type']['und']['#options'] = $options;
  }
}