<?php

function events_signup_menu(){
  $items = array();
  
  $items['event/signup/%'] = array(
    'title' => 'Signup',
    'description' => 'Signup for an event',
    'page callback' => 'events_signup_display',
    'page arguments' => array(2),
    'access callback' => array(1),
    'type' => MENU_CALLBACK,
  );
  
  $items['event/registration/%'] = array(
    'title' => 'Registration',
    'description' => 'Signup for an event',
    'page callback' => 'events_signup_display',
    'page arguments' => array(2),
    'access arguments' => TRUE,
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function events_signup_display($nid){

  $form = events_signup_form();
  
  return $form;
  
}

function events_signup_form(){
  
  module_load_include('inc', 'node', 'node.pages');
  
  $form = node_add('event_registration');
  
  $output = drupal_render($form);
  
  return $output;
  
}

function events_signup_form_alter(&$form, &$form_state, $form_id){
  if($form_id == 'event_registration_node_form'){
  
    global $user;
    
    //set default values if the user is logged in
    
    if($user->uid > 0){
    
      $form['field_register_full_name']['und'][0]['value']['#default_value'] = $user->name;
      
      $form['uid_id'] = array(
        '#type' => 'value',
        '#value' => $user->uid,
      );
    
    }
    
    //remove the node options
    
    $form['options']['status'] = array(
      '#type' => 'value',
      '#value' => '1',
    );
    
    $form['options'] = array(
      '#type' => 'container',
      '#title' => '',
    );
    
    hide($form['additional_settings']);
    
    //pass event id and user
  
    $form['event_id'] = array(
      '#type' => 'value',
      '#value' => arg(2),
    );
    
    unset($form['body']);
    
    //set title of form to the event title and date
    $node = node_load(arg(2));
        
    $title = '<h1>' . $node->title . ' Signup ';
    $title .= (!empty($node->field_event_date)) ? '<div class="date day">' . date('F d, Y',strtotime($node->field_event_date['und'][0]['value'])) . '</div><div class="date time">' . date('g:ia',strtotime($node->field_event_date['und'][0]['value'])) . '</div>' : '';
    
    $title .= '</h1>';

    $form['title']['#prefix'] = $title;
    
    drupal_set_title('');
  
  }
}

